// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVtjqMcYOKs_TMQnxZLo6SXgQvsX7ByIs',
    appId: '1:568033864847:web:8b9a9488a4a8d39ead94fa',
    messagingSenderId: '568033864847',
    projectId: 'sistemaharas-7e158',
    authDomain: 'sistemaharas-7e158.firebaseapp.com',
    storageBucket: 'sistemaharas-7e158.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjdSxbpzZnZ7WLpg8rm80cyB5MwaFOnDY',
    appId: '1:568033864847:android:bf3dfc4598f2f4d8ad94fa',
    messagingSenderId: '568033864847',
    projectId: 'sistemaharas-7e158',
    storageBucket: 'sistemaharas-7e158.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCdCtCq9125Nz_r59gZLWMmxuemiUoY8g',
    appId: '1:568033864847:ios:e0292df22c670f20ad94fa',
    messagingSenderId: '568033864847',
    projectId: 'sistemaharas-7e158',
    storageBucket: 'sistemaharas-7e158.firebasestorage.app',
    iosBundleId: 'com.example.gestorHaras',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCdCtCq9125Nz_r59gZLWMmxuemiUoY8g',
    appId: '1:568033864847:ios:e0292df22c670f20ad94fa',
    messagingSenderId: '568033864847',
    projectId: 'sistemaharas-7e158',
    storageBucket: 'sistemaharas-7e158.firebasestorage.app',
    iosBundleId: 'com.example.gestorHaras',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVtjqMcYOKs_TMQnxZLo6SXgQvsX7ByIs',
    appId: '1:568033864847:web:caef928d73a1b9dcad94fa',
    messagingSenderId: '568033864847',
    projectId: 'sistemaharas-7e158',
    authDomain: 'sistemaharas-7e158.firebaseapp.com',
    storageBucket: 'sistemaharas-7e158.firebasestorage.app',
  );
}
